### ISSUE TITLE
Documentation is lacking

### ISSUE THREAD

**Issue by boazeg** [Azure-Samples/live-video-analytics-iot-edge-csharp#25]
We are looking to leverage LVA as part of a solution we are building on IoT Edge and we find that the documentation offered is not very useful and does not allow any insight into how to configure LVA to achieve the desired results.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.media.livevideoanalytics.edge.models?view=azure-dotnet-preview is pretty much useless without additional information beyond names and data types of the different classes/methods/interfaces/etc.

**Comment by gadamilan** [comment]
@boazeg 
The link you shared above is for the .NET SDK which is in the process of being published. You can get started with LVA by using these doc pages https://docs.microsoft.com/en-us/azure/media-services/live-video-analytics-edge/get-started-detect-motion-emit-events-quickstart and https://docs.microsoft.com/en-us/azure/media-services/live-video-analytics-edge/detect-motion-emit-events-quickstart?pivots=programming-language-csharp. These pages explain how to use the sample code provided in this repo. There are other quickstarts and tutorials as well.

**Comment by gadamilan** [comment]
@boazeg 
Closing this issue. Please let us know if you have more questions on this.

**Comment by boazeg** [comment]
@gadamilan 
The quickstart doc pages are indeed useful. We've been using https://docs.microsoft.com/en-us/azure/media-services/live-video-analytics-edge/detect-motion-record-video-clips-media-services-quickstart as a base to what we are trying to build. However, we are starting to experience behavior that is not clear and need more information regrading the configuration of the different media graph components. For example, we are experiencing multiple motion events triggered for what it seems like a single incident, at least by looking at the files captured by MediaGraphFileSink. In addition, the latency we are experiencing in terms of notification of motion events from when they actually happen causes delays that break our scenario.
If you like, we can share more information offline.

**Comment by gadamilan** [comment]
I am glad that the quickstart helped.
Can you clarify what you are trying to do with motion events? That will help us provide more information on how best to realize your scenario with the events? 

Also, please elaborate some more on the latency issue.

**Comment by gadamilan** [comment]
Closing due to lack of response
