### ISSUE TITLE
default launch.json console parameter does not allow stdin

### ISSUE THREAD

**Issue by dvescovi1** [Azure-Samples/live-video-analytics-iot-edge-csharp#51]
when trying to run the debugger with the cloud-to-device-console project the default launch.json creates a configuration with the parameter  "console": "internalConsole". This does not work when using the VS Code with the integrated terminal as the documentation states. internalConsole does not allow keyboard input. Changing parameter to "console" : "integratedTerminal" fixes the problem. This fact needs to included in the documentation.

**Comment by naiteeks** [comment]
THank you @dvescovi1.
That is correct. I have seen many folks new to development in VSCode face this issue. We will work on putting this in our repos going ahead.
